### ISSUE TITLE
what license is this mod licensed under?

### ISSUE THREAD

**Issue by iamdew132** [WMF-Industries/NeonNights2#2]
pls answer :(

**Comment by WMF-Industries** [comment]
none cuz i was too lazy to add one, but do feel free to do anything you want with it

**Comment by WilloIzCitron** [comment]
> none cuz i was too lazy to add one, but do feel free to do anything you want with it

anyway, it looks like inconsistent how the mindustry mod licensing work
> Requires use GPL-v3

I use MIT because yeah there's no copylefting (GPL compatible). as you want to add license or not, is your decision not my statement

**Comment by iamdew132** [comment]
ok.
